### ISSUE TITLE
Support of ember-cli 3.5

### ISSUE THREAD

**Issue by ncoden** [vitch/ember-cli-webfont#13]
Ember CLI 3.5 migrated to Broccoli 2. See the [migration notes](https://www.emberjs.com/blog/2018/10/15/ember-3-5-released.html#toc_new-features-3)

This addon relies on Broccoli 1 API and produces build the following error during the build:
```
WARNING: Invalid Broccoli2 node detected, falling back to broccoli-builder. Broccoli error:
---------------
Webfont: The .read/.rebuild API is no longer supported as of Broccoli 1.0. Plugins must now derive from broccoli-plugin. https://github.com/broccolijs/broccoli/blob/master/docs/broccoli-1-0-plugin-api.md
used as input node to Funnel
-~- created here: -~-
    at Funnel.Plugin (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/2017/Clevy/repo/app/node_modules/broccoli-plugin/index.js:7:31)
    at new Funnel (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/2017/Clevy/repo/app/node_modules/ember-cli-webfont/node_modules/broccoli-funnel/index.js:44:10)
    at Class.treeForStyles (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/2017/Clevy/repo/app/node_modules/ember-cli-webfont/index.js:43:15)
    at Class._treeFor (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/2017/Clevy/repo/app/node_modules/ember-cli/lib/models/addon.js:618:33)
    at Class.treeFor (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/2017/Clevy/repo/app/node_modules/ember-cli/lib/models/addon.js:578:21)
    at project.addons.reduce (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/2017/Clevy/repo/app/node_modules/ember-cli/lib/broccoli/ember-app.js:700:26)
    at Array.reduce (<anonymous>)
    at EmberApp._addonTreesFor (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/2017/Clevy/repo/app/node_modules/ember-cli/lib/broccoli/ember-app.js:698:32)
    at EmberApp.addonTreesFor (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/2017/Clevy/repo/app/node_modules/ember-cli/lib/broccoli/ember-app.js:722:17)
    at EmberApp.getStyles (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/2017/Clevy/repo/app/node_modules/ember-cli/lib/broccoli/ember-app.js:1085:23)
    at EmberApp.toArray (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/2017/Clevy/repo/app/node_modules/ember-cli/lib/broccoli/ember-app.js:1618:12)
    at EmberApp.toTree (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/2017/Clevy/repo/app/node_modules/ember-cli/lib/broccoli/ember-app.js:1750:36)
    at module.exports (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/2017/Clevy/repo/app/ember-cli-build.js:195:14)
    at Builder.readBuildFile (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/2017/Clevy/repo/app/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/2017/Clevy/repo/app/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/2017/Clevy/repo/app/node_modules/ember-cli/lib/models/builder.js:32:10)
    at ServeTask.run (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/2017/Clevy/repo/app/node_modules/ember-cli/lib/tasks/serve.js:45:55)
    at Promise.resolve.then (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/2017/Clevy/repo/app/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatcher (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/2017/Clevy/repo/app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/2017/Clevy/repo/app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/ncoden/Documents/Documents/Projects/Programmation/Web/2017/Clevy/repo/app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/ncoden/Documents/Documents/Projects/Programmation/Web/2017/Clevy/repo/app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
-~- (end) -~----------------
```

**Comment by ncoden** [comment]
👋 @vitch

**Comment by ncoden** [comment]
Closing. I was using an old version of ember-cli-webfont.
