### ISSUE TITLE
Using inside a ember engine

### ISSUE THREAD

**Issue by brunowego** [vitch/ember-cli-webfont#3]
Hi, I wish report a issue with Ember Engine. Works great if put `ember-cli-webfont` in `devDependencies` but if change it to `dependencies`, it's broken.

Inside `ember-cli-build.js` I have this settings:

```js
/* eslint-env node */
const EmberAddon = require('ember-cli/lib/broccoli/ember-addon');

module.exports = function(defaults) {
  const app = new EmberAddon(defaults, {
    webfont: {
      path: 'addon/icons',
      options: {
        dest: 'engines-dist/apollo-identify/assets/webfonts/',
        cssFontsPath: '/engines-dist/apollo-identify/assets/webfonts/',
        templateOptions: {
          classPrefix: 'i--',
          baseClass: 'i'
        }
      }
    }
  });

  return app.toTree();
};
```

Take a look at the full stack:

```sh
Cannot read property 'options' of undefined
TypeError: Cannot read property 'options' of undefined
    at Class.webfontPath (/secret/apollo-identify-engine/node_modules/ember-cli-webfont/index.js:29:17)
    at Class.treeForStyles (/secret/apollo-identify-engine/node_modules/ember-cli-webfont/index.js:36:21)
    at Class._treeFor (/secret/apollo-identify-engine/node_modules/ember-cli/lib/models/addon.js:517:33)
    at Class.treeFor (/secret/apollo-identify-engine/node_modules/ember-cli/lib/models/addon.js:477:21)
    at addons.map.addon (/secret/apollo-identify-engine/node_modules/ember-cli/lib/models/addon.js:346:34)
    at Array.map (native)
    at Class.eachAddonInvoke (/secret/apollo-identify-engine/node_modules/ember-cli/lib/models/addon.js:344:24)
    at Class.buildEngineStyleTree (/secret/apollo-identify-engine/node_modules/ember-engines/lib/engine-addon.js:239:35)
    at Class._memoize (/secret/apollo-identify-engine/node_modules/ember-engines/lib/utils/memoize.js:10:38)
    at Class.compileLazyEngineStyles (/secret/apollo-identify-engine/node_modules/ember-engines/lib/engine-addon.js:426:53)
```

---

Related with https://github.com/ember-engines/ember-engines/issues/346

**Comment by vitch** [comment]
Fixed by #4
